---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: conjurized-container
    image: conjurinc/cli5
    dockercommands: true
    entrypoint: sleep
    command: infinity
    networks:
      - name: ansibleroleconjur_default
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: retrieve-secret-in-remote
  test_sequence:
    - destroy
    - create
    - converge
    #      - lint
    - verify
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
