---
- name: Converge
  hosts: conjurized-container
  become: true
  vars:
    CONJUR_ACCOUNT: cucumber
    CONJUR_APPLIANCE_URL: http://conjur:3000
    CONJUR_CUSTOM_AUTHN_API_KEY: "{{lookup('env', 'CONJUR_CUSTOM_AUTHN_API_KEY')}}"
    molecule_templates_directory: "{{ lookup('env', 'MOLECULE_SCENARIO_DIRECTORY') }}/../templates"
  tasks:
    - name: Render /etc/conjur.conf
      template:
        src: "{{ molecule_templates_directory}}/conjur.conf.j2"
        dest: /etc/conjur.conf
        mode: 0644

    - name: Render /etc/conjur.identity
      template:
        src: "{{ molecule_templates_directory}}/conjur.identity.j2"
        dest: /etc/conjur.identity
        mode: 0644

    - name: Retrieve secrets with target identity
      retrieve_conjur_variable:
        variables:
          RETRIEVED_PASSWORD: ansible/target-password
          ANOTHER_RETRIEVED_PASSWORD: ansible/another-target-password
      register: result

    - name: Do something with the secret
      shell: echo "{{result.secrets['RETRIEVED_PASSWORD']}},{{result.secrets['ANOTHER_RETRIEVED_PASSWORD']}}" > ./conjur_secrets.txt
