---
- name: Converge
  hosts: conjurized-container
  become: true
  roles:
    - role: ansible-role-conjur/configure-conjur-identity
      conjur_account: cucumber
      conjur_appliance_url: "http://conjur:3000"
      conjur_host_factory_token: "{{lookup('env', 'HFTOKEN')}}"
      conjur_ssl_certificate: "{{lookup('file', '../conjur.pem')}}"
      conjur_host_name: "conjur_{{ ansible_hostname }}"
      conjur_validate_certs: no
      conjur_ssh_enable: no
